version: '3.1'

services:
  mysql:
    image: mysql:5.7
    command: >
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
    environment:
      - MYSQL_DATABASE=workrecord
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_USER=default
      - MYSQL_PASSWORD=password
      - TZ=Asia/Tokyo
    ports:
      - "3306:3306"
    volumes:
      - ./db/mysql_data:/var/lib/mysql

  workrecord-go:
    image: workrecord-go:0.1.0
    volumes:
      - ./src:/go/src/app
    ports:
      - "8080:8080"
